### ISSUE TITLE
Cache not clearing after purchase

### ISSUE THREAD

**Issue by craigs100** [UmbHost/UmbCheckout#25]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V10.6.1

### Bug summary

Each call to Stripe contains not only the current order line items, but all the other ones as well in the same browser session.

### Specifics

Each call to Stripe contains not only the current order line items, but all the other ones as well in the same browser session.

### Steps to reproduce

Each call to Stripe contains not only the current order line items, but all the other ones as well in the same browser session.

### Expected result / actual result

Expected a clean basked each time, but appears to not empty the server session after payment succeeds.

**Comment by AaronSadlerUK** [comment]
This is fixed in RC10
