### ISSUE TITLE
Basket empty on first call

### ISSUE THREAD

**Issue by craigs100** [UmbHost/UmbCheckout#26]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

The first purchase after a restart fails due to an empty basket.  The second attempt goes through to Stripe ok.

### Steps to reproduce

1. With a working shop. Shut down the site and restart it. 
2. Make a single line purchase.
3. Notice the Stripe interface does not appear. (My installation returns to it's Order Failed page)
4. Error in log: "You passed an empty string for 'line_items'. We assume empty values are an attempt to unset a parameter; however 'line_items' cannot be unset. You should remove 'line_items' from your request or supply a non-empty value."
5. Try again.
6. Note purchase goes through as normal.

### Expected result / actual result

Expected the sale to progress as normal.

Stripe interface doesn't appear, error in log.

**Comment by AaronSadlerUK** [comment]
When the lineitems are empty it now redirects to the Basket with a TempData set of "TempData["UmbCheckout_EmptyBasket"] = true;"

After a site restart the basket will be empty as the dotnet session is cleared.

To persist after a restart you need to use the Addons package and enable cookie storage
