### ISSUE TITLE
UmbCheckout Settings Label Not Loading

### ISSUE THREAD

**Issue by AaronSadlerUK** [UmbHost/UmbCheckout#51]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.7.0

### Bug summary

The label in the settings section for UmbCheckout is not loading / missing

### Steps to reproduce

Install UmbCheckout and then head to the settings section

### Expected result / actual result

The Label should say UmbCheckout instead it says [umbCheckout]

![image](https://github.com/UmbHost/UmbCheckout/assets/9937803/9d6f3ce5-74bd-4306-8e6a-9759565fc642)

**Comment by 0xlarmideh** [comment]
Can I work on this?
